{{- if .Values.limitRange.create }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "py-app.fullname" . }}
  labels:
    {{- include "py-app.labels" . | nindent 4 }}
spec:
  limits: {{ .Values.limitRange.limits | toYaml | nindent 2 }}
{{- end -}}