{{- range $name, $val := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{include "pgbouncer.name" $ }}-{{ $name }}"
  labels:
    {{- include "pgbouncer.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync,Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ default "1h" $val.refreshInterval }}           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $val.secretStoreName }} # name of the SecretStore (or kind specified)
  target:
    name: {{ $val.targetName }}
    creationPolicy: {{ default "Owner" $val.targetCreationPolicy }}
    deletionPolicy: {{ default "Retain" $val.targetDeletionPolicy }}
  dataFrom: {{ toYaml $val.dataFrom | nindent 4 }}
{{ end -}}
