name: Releasing charts

on:
  push:
    branches:
      - main
      - master

jobs:
  upload_helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - py-app
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
        with:
          version: latest
      - name: Build Helm chart
        run: |
          helm package --app-version "${{ github.ref_name }}" --dependency-update ./charts/${{ matrix.chart }}
          helm show chart *.tgz
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          helm push *.tgz oci://ghcr.io/intreecom/charts
        env:
          HELM_EXPERIMENTAL_OCI: 1
